name: Creation of first workflow ADA School
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
      - name: clean project
        run: mvn clean
      - name: run the test
        run: mvn test
      - name: creation .jar and installing
        rum: mvn install